services:
  db:
    image: postgres:16
    container_name: pg-monolito
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mon0lito_AWS2025!
      POSTGRES_DB: monolito_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d monolito_ecommerce"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    image: monolito-app:latest
    container_name: monolito-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: monolito_ecommerce
      DB_USER: postgres
      DB_PASSWORD: Mon0lito_AWS2025!
      DB_SSLMODE: disable
    # si tu app no expone HTTP, puedes omitir ports:
    # ports:
    #   - "8080:8080"

volumes:
  pgdata:
